doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        types:
            account_number: 'App\Account\Infrastructure\Db\AccountNumberType'
            wallet_id: 'App\Account\Infrastructure\Db\WalletIdType'
            big_decimal: 'App\Kernel\BigDecimal\BigDecimalType'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Identity:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Identity/Domain'
                prefix: 'App\Identity\Domain'
                alias: Identity
            Account:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Account/Domain'
                prefix: 'App\Account\Domain'
                alias: Account
            Negotiation:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Negotiation/Domain'
                prefix: 'App\Negotiation\Domain'
                alias: Negotiation
            Currency:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Currency/Domain'
                prefix: 'App\Currency\Domain'
                alias: Currency
            Quoting:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Quoting/Domain'
                prefix: 'App\Quoting\Domain'
                alias: Quoting
            Promotion:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Promotion/Domain'
                prefix: 'App\Promotion\Domain'
                alias: Promotion
            PromotionSaga:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/PromotionSaga'
                prefix: 'App\PromotionSaga'
                alias: PromotionSaga
            Kernel:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Kernel'
                prefix: 'App\Kernel'
                alias: Kernel

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
