nelmio_api_doc:
  areas:
    default:
      path_patterns:
        - ^/quotes/
        - ^/accounts/
        - ^/currency-pair/
        - ^/identities/
        - ^/identity/
        - ^/identity
        - ^/negotiations/
        - ^/riskassessment/

